force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>Object used for logging purpose (debug, callouts, exceptions...)</description>
    <label>Log</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{DD}_{0000000000}</displayFormat>
        <label>Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/ApexClass__c.field-meta.xml
<CustomField>
    <fullName>ApexClass__c</fullName>
    <description>Apex class that generates the log (from the start)</description>
    <label>Apex Class</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/ApexMethod__c.field-meta.xml
<CustomField>
    <fullName>ApexMethod__c</fullName>
    <description>Apex method that generates the log (from the start)</description>
    <label>Apex Method</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/APIName__c.field-meta.xml
<CustomField>
    <fullName>APIName__c</fullName>
    <description>API Name</description>
    <label>API Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>referential.location.v2</fullName>
            </value>
            <value>
                <fullName>shipping.shipment.v1</fullName>
            </value>
            <value>
                <fullName>WIMB</fullName>
            </value>
            <value>
                <fullName>vesseloperation.voyage.v1</fullName>
            </value>
            <value>
                <fullName>user.pingfederate.v1</fullName>
            </value>
            <value>
                <fullName>shipping.shipment.v2</fullName>
            </value>
            <value>
                <fullName>logistic.tracking.wimb</fullName>
            </value>
            <value>
                <fullName>invoicing.advanced.v1</fullName>
            </value>
            <value>
                <fullName>vesseloperation.voyage.localreferences.v1</fullName>
            </value>
            <value>
                <fullName>shipping.shipment.notification.advance.v1</fullName>
            </value>
            <value>
                <fullName>shipping.shippingdocument.v1</fullName>
            </value>
            <value>
                <fullName>shipping.shipment.shipmentrequest.v1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/fields/CorrelationId__c.field-meta.xml
<CustomField>
    <fullName>CorrelationId__c</fullName>
    <description>Correlation ID returns by the API Management system</description>
    <label>Correlation ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Log description</description>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <label>Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <description>Callout endpoint</description>
    <label>Endpoint</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/EntityData__c.field-meta.xml
<CustomField>
    <fullName>EntityData__c</fullName>
    <description>Entity Data</description>
    <label>Entity Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/EntityId__c.field-meta.xml
<CustomField>
    <fullName>EntityId__c</fullName>
    <description>Main entity ID</description>
    <label>Entity ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/ExceptionType__c.field-meta.xml
<CustomField>
    <fullName>ExceptionType__c</fullName>
    <description>Exception Type (NullPointerException, CalloutException etc...)</description>
    <label>Exception Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Identifier__c.field-meta.xml
<CustomField>
    <fullName>Identifier__c</fullName>
    <description>Log identifier</description>
    <label>Identifier</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Log__c/fields/RequestBody__c.field-meta.xml
<CustomField>
    <fullName>RequestBody__c</fullName>
    <description>HTTP Request Body</description>
    <label>Request Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/RequestHeader__c.field-meta.xml
<CustomField>
    <fullName>RequestHeader__c</fullName>
    <description>Request Header</description>
    <label>Request Header</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/ResponseBody__c.field-meta.xml
<CustomField>
    <fullName>ResponseBody__c</fullName>
    <description>HTTP Response Body</description>
    <label>Response Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/ResponseHeader__c.field-meta.xml
<CustomField>
    <fullName>ResponseHeader__c</fullName>
    <description>HTTP Response Header</description>
    <label>Response Header</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/ResponseStatus__c.field-meta.xml
<CustomField>
    <fullName>ResponseStatus__c</fullName>
    <description>HTTP Response Status</description>
    <label>Response Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/ResponseStatusCode__c.field-meta.xml
<CustomField>
    <fullName>ResponseStatusCode__c</fullName>
    <description>HTTP Response status code</description>
    <label>Response Status Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/RunningUser__c.field-meta.xml
<CustomField>
    <fullName>RunningUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Running User that generates the log record</description>
    <label>Running User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <description>Error Stack Trace</description>
    <label>Stack Trace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Log type (Error, debug...)</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
                <default>true</default>
                <label>Error</label>
            </value>
            <value>
                <fullName>Debug</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/recordTypes/Apex.recordType-meta.xml
<RecordType>
    <fullName>Apex</fullName>
    <active>true</active>
    <description>Apex log</description>
    <label>Apex</label>
</RecordType>

force-app/main/default/objects/Log__c/recordTypes/Callout.recordType-meta.xml
<RecordType>
    <fullName>Callout</fullName>
    <active>true</active>
    <description>Callout logs</description>
    <label>Callout</label>
</RecordType>

force-app/main/default/objects/LogEvent__e/LogEvent__e.object-meta.xml
<CustomObject>
    <description>Log Event</description>
    <label>LogEvent</label>
    <pluralLabel>LogsEvent</pluralLabel>
</CustomObject>

force-app/main/default/objects/LogEvent__e/fields/ApexClass__c.field-meta.xml
<CustomField>
    <fullName>ApexClass__c</fullName>
    <label>Apex Class</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/ApexMethod__c.field-meta.xml
<CustomField>
    <fullName>ApexMethod__c</fullName>
    <label>Apex Method</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/APIName__c.field-meta.xml
<CustomField>
    <fullName>APIName__c</fullName>
    <label>APiName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/CorrelationId__c.field-meta.xml
<CustomField>
    <fullName>CorrelationId__c</fullName>
    <description>Correlation ID returns by the API Management System</description>
    <label>Correlation ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description</description>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <label>Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/EntityData__c.field-meta.xml
<CustomField>
    <fullName>EntityData__c</fullName>
    <description>Entity Data</description>
    <label>Entity Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/EntityID__c.field-meta.xml
<CustomField>
    <fullName>EntityID__c</fullName>
    <label>Entity ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/ExceptionType__c.field-meta.xml
<CustomField>
    <fullName>ExceptionType__c</fullName>
    <description>Exception Type</description>
    <label>Exception Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/Identifier__c.field-meta.xml
<CustomField>
    <fullName>Identifier__c</fullName>
    <label>Identifier</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/RecordTypeId__c.field-meta.xml
<CustomField>
    <fullName>RecordTypeId__c</fullName>
    <label>Record Type ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/RequestBody__c.field-meta.xml
<CustomField>
    <fullName>RequestBody__c</fullName>
    <label>Request Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/RequestHeader__c.field-meta.xml
<CustomField>
    <fullName>RequestHeader__c</fullName>
    <label>Request Header</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/ResponseBody__c.field-meta.xml
<CustomField>
    <fullName>ResponseBody__c</fullName>
    <label>Response Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/ResponseHeader__c.field-meta.xml
<CustomField>
    <fullName>ResponseHeader__c</fullName>
    <label>Response Header</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/ResponseStatus__c.field-meta.xml
<CustomField>
    <fullName>ResponseStatus__c</fullName>
    <label>Response Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/ResponseStatusCode__c.field-meta.xml
<CustomField>
    <fullName>ResponseStatusCode__c</fullName>
    <label>Response Status Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/RunningUser__c.field-meta.xml
<CustomField>
    <fullName>RunningUser__c</fullName>
    <description>User ID that generates the log record</description>
    <label>Running User</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <label>Stack Trace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/UTIL_Logger.cls
/**
* @author Gil Avignon
* @date 01/08/2018
* @description Utility Class for Log Management
* @group Utility
*/
public class UTIL_Logger {
    private static Map<String, Id> recordTypesByDeveloperName = UTIL_RecordType.getRecordTypesDeveloper('Log__c');
    public static List<LogEvent__e> logEvents = new List<LogEvent__e>();
    private static Integer cpt = 0;
    // private static LogSettings__c mySettings = LogSettings__c.getInstance();
    
    @InvocableMethod(label='Log Error' description='Log error in Log__c custom object.')
    public static void logEventFromFlow(List<FlowRequest> flowRequest){
        String recordType = 'Apex';
        if(flowRequest[0].recordType != null){
            recordType = flowRequest[0].recordType;
        }
    
        String recordTypeId = recordType == 'Callout' ? LOG_CALLOUT_RTID : LOG_APEX_RTID;
        LogEvent__e logEvent = new LogEvent__e(
                Identifier__c = generateId(),
                APIName__c = flowRequest[0].apiName,
                ApexClass__c = flowRequest[0].apexClass.left(50),
                ApexMethod__c = flowRequest[0].apexMethod.left(50),
                Description__c = flowRequest[0].errorMessage.left(255),
                Details__c = flowRequest[0].errorMessage.left(131072),
                Type__c = C3S_UTI01_Constants.LOG_TYPE_ERROR,
                EntityId__c = flowRequest[0].entityId.left(18),
                RecordTypeId__c = recordTypeId,
                ResponseStatusCode__c = flowRequest[0].responseStatusCode,
                ResponseBody__c = flowRequest[0].errorMessage.left(131072),
                RunningUser__c = UserInfo.getUserId(),
                StackTrace__c = flowRequest[0].errorMessage.left(131072)
        );
        if(Test.isRunningTest()){
            logEvent.Identifier__c = String.valueOf(cpt);
            cpt++;
        }
        logEvents.add(logEvent);
        commitLogEvents();
    }

    /**
    * @author Gil Avignon
    * @date 25/07/2018
    * @description Create log record for Apex errors
    * @param apiName API Name
    * @param description Error description
    * @param apexClass Calling apex class
    * @param apexMethod Calling apex method
    * @param endpoint Endpoint
    * @param entityId Entity ID
    * @param headerInfo Header informations
    * @return LogEvent__e Generated log event
    */
    public static LogEvent__e logEvent(String apiName, String description, String apexClass, String apexMethod, String endpoint, Id entityId, String headerInfo){
        LogEvent__e logEvent = new LogEvent__e(
                Identifier__c = generateId(),
                APIName__c = apiName,
                ApexClass__c = apexClass,
                ApexMethod__c = apexMethod,
                Description__c = description.left(255),
                Details__c = description,
                Type__c = UTIL_Constants.LOG_TYPE_ERROR,
                Endpoint__c = endpoint,
                RequestHeader__c = headerInfo,
                RunningUser__c = UserInfo.getUserId(),
                EntityId__c = entityId,
                RecordTypeId__c = recordTypesByDeveloperName.get('Apex')
        );
        if(Test.isRunningTest()){
            logEvent.Identifier__c = String.valueOf(cpt);
            cpt++;
        }
        logEvents.add(logEvent);

        return logEvent;
    }

    /**
    * @author Gil Avignon
    * @date 02/07/2019
    * @description Create debug log record for Apex
    * @param description Error description
    * @param apexClass Calling apex class
    * @param apexMethod Calling apex method
    * @param entityId Entity ID
    * @return LogEvent__e Generated log event
    */
    public static void debug(String description,String entityData, String apexClass, String apexMethod, Id entityId){
        // if(mySettings.Active__c && mySettings.ApexClass__c == apexClass && mySettings.ApexMethod__c == apexMethod){
            LogEvent__e logEvent = new LogEvent__e(
                    Identifier__c = generateId(),
                    ApexClass__c = apexClass,
                    ApexMethod__c = apexMethod,
                    Description__c = description.left(255),
                    Details__c = description,
                    Type__c = UTIL_Constants.LOG_TYPE_DEBUG,
                    RunningUser__c = UserInfo.getUserId(),
                    EntityId__c = entityId,
                    EntityData__c = entityData,
                    RecordTypeId__c = recordTypesByDeveloperName.get('Apex')
            );
            if(Test.isRunningTest()){
                logEvent.Identifier__c = String.valueOf(cpt);
                cpt++;
            }
            logEvents.add(logEvent);
        // }
    }


    /**
    * @author Gil Avignon
    * @date 25/07/2018
    * @description Create log record for Apex errors
    * @param apiName API Name
    * @param e Exception
    * @param apexClass Calling apex class
    * @param apexMethod Calling apex method
    * @param endpoint Endpoint
    * @param entityId Entity ID
    * @param headerInfo Header informations
    * @return LogEvent__e Generated log event
    */
    public static LogEvent__e logEventFromException(String apiName, Exception e, String apexClass, String apexMethod, String endpoint, Id entityId, String headerInfo){
        String recordTypeId = recordTypesByDeveloperName.get('Apex');
        if(e instanceof CalloutException){
            recordTypeId = recordTypesByDeveloperName.get('Callout');
        }

        LogEvent__e logEvent = new LogEvent__e(
                Identifier__c = generateId(),
                APIName__c = apiName,
                ApexClass__c = apexClass,
                ApexMethod__c = apexMethod,
                Description__c = e.getMessage().left(255),
                Details__c = e.getMessage(),
                Type__c = UTIL_Constants.LOG_TYPE_ERROR,
                Endpoint__c = endpoint,
                ExceptionType__c = e.getTypeName(),
                RequestHeader__c = headerInfo,
                EntityId__c = entityId,
                RecordTypeId__c = recordTypeId,
                RunningUser__c = UserInfo.getUserId(),
                StackTrace__c = e.getStackTraceString()
        );
        if(Test.isRunningTest()){
            logEvent.Identifier__c = String.valueOf(cpt);
            cpt++;
        }

        logEvents.add(logEvent);

        return logEvent;
    }

    /**
    * @author Gil Avignon
    * @date 25/07/2018
    * @description Create log record for Apex errors
    * @param apiName API Name
    * @param e Exception
    * @param apexClass Calling apex class
    * @param apexMethod Calling apex method
    * @param endpoint Endpoint
    * @param entityId Entity ID
    * @param headerInfo Header informations
    * @return LogEvent__e Generated log event
    */
    public static LogEvent__e logEventFromExceptionWithData(String apiName, Exception e, String apexClass, String apexMethod, String endpoint, Id entityId, String entityData, String headerInfo){
        String recordTypeId = recordTypesByDeveloperName.get('Apex');
        if(e instanceof CalloutException){
            recordTypeId = recordTypesByDeveloperName.get('Callout');
        }

        LogEvent__e logEvent = new LogEvent__e(
                Identifier__c = generateId(),
                APIName__c = apiName,
                ApexClass__c = apexClass,
                ApexMethod__c = apexMethod,
                Description__c = e.getMessage().left(255),
                Details__c = e.getMessage(),
                Type__c = UTIL_Constants.LOG_TYPE_ERROR,
                Endpoint__c = endpoint,
                ExceptionType__c = e.getTypeName(),
                RequestHeader__c = headerInfo,
                EntityId__c = entityId,
                EntityData__c = entityData,
                RecordTypeId__c = recordTypeId,
                RunningUser__c = UserInfo.getUserId(),
                StackTrace__c = e.getStackTraceString()
        );
        if(Test.isRunningTest()){
            logEvent.Identifier__c = String.valueOf(cpt);
            cpt++;
        }

        logEvents.add(logEvent);

        return logEvent;
    }




    /**
    * @author Gil Avignon
    * @date 25/07/2018
    * @description Create log record for Apex errors
    * @param apiName API Name
    * @param apexClass Calling apex class
    * @param apexMethod Calling apex method
    * @param request HTTP Request
    * @param response HTTP Response
    * @param debugLogs Debug mode
    * @return LogEvent__e Generated log event
    */
    public static LogEvent__e logEvent(String apiName, String apexClass, String apexMethod, HttpRequest request, HttpResponse response, Boolean debugLogs) {
        // Manage Request Headers
        String headers = '';
        if(request.getHeader(UTIL_Constants.REQUEST_HEADER_KEY) != null){
            headers += UTIL_Constants.REQUEST_HEADER_KEY + ': ' + request.getHeader(UTIL_Constants.REQUEST_HEADER_KEY) + '\n';
        }
        if(request.getHeader(UTIL_Constants.REQUEST_HEADER_KEYID) != null){
            headers += UTIL_Constants.REQUEST_HEADER_KEYID + ': ' + request.getHeader(UTIL_Constants.REQUEST_HEADER_KEYID) + '\n';
        }
        if(request.getHeader(UTIL_Constants.REQUEST_HEADER_TRACE_ORG) != null){
            headers += UTIL_Constants.REQUEST_HEADER_TRACE_ORG + ': ' + request.getHeader(UTIL_Constants.REQUEST_HEADER_TRACE_ORG) + '\n';
        }
        if(request.getHeader(UTIL_Constants.REQUEST_HEADER_TRACE_USER) != null){
            headers += UTIL_Constants.REQUEST_HEADER_TRACE_USER + ': ' + request.getHeader(UTIL_Constants.REQUEST_HEADER_TRACE_USER) + '\n';
        }
        if(request.getHeader(UTIL_Constants.REQUEST_HEADER_TRACE_ENTITY) != null){
            headers += UTIL_Constants.REQUEST_HEADER_TRACE_ENTITY + ': ' + request.getHeader(UTIL_Constants.REQUEST_HEADER_TRACE_ENTITY);
        }

        // Manage Response Headers
        String respHeaders = '';
        List<String> respHeaderKeys = response.getHeaderKeys();
        for(String keyHeader : respHeaderKeys){
            respHeaders += keyHeader + ': ' + response.getHeader(keyHeader) + '\n';
        }

        String correlationId = '';
        // Manage Correlation ID
        if(response.getHeader('X-CorrelationID') != null){
            correlationId = response.getHeader('X-CorrelationID');
        }

        // Prettify Body
        Object reqBodyObj = null;
        String reqBodyString = '';
        if(request.getBody() != null && request.getBody() != ''){
            reqBodyObj = JSON.deserializeUntyped(request.getBody());
            if(reqBodyObj != null){
                reqBodyString = JSON.serializePretty(reqBodyObj);
            }
        }
        Object respBodyObj = null;
        String respBodyString = '';
        if(response.getBody() != null && response.getBody() != ''){
            respBodyObj = JSON.deserializeUntyped(response.getBody());
            if(respBodyObj != null){
                respBodyString = JSON.serializePretty(respBodyObj);
            }
        }

        // Create log
        LogEvent__e logEvent = new LogEvent__e(
                Identifier__c = generateId(),
                APIName__c = apiName,
                ApexClass__c = apexClass,
                ApexMethod__c = apexMethod,
                CorrelationId__c = correlationId,
                Type__c = debugLogs ? UTIL_Constants.LOG_TYPE_DEBUG : UTIL_Constants.LOG_TYPE_ERROR,
                Endpoint__c = request.getEndpoint(),
                RequestHeader__c = headers,
                RequestBody__c = reqBodyString,
                ResponseHeader__c = respHeaders,
                ResponseBody__c = respBodyString,
                ResponseStatus__c = String.valueOf(response.getStatus()),
                ResponseStatusCode__c = String.valueOf(response.getStatusCode()),
                RunningUser__c = UserInfo.getUserId(),
                EntityId__c = request.getHeader(UTIL_Constants.REQUEST_HEADER_TRACE_ENTITY),
                RecordTypeId__c = recordTypesByDeveloperName.get('Callout'),
                StackTrace__c = ''
        );
        if(Test.isRunningTest()){
            logEvent.Identifier__c = String.valueOf(cpt);
            cpt++;
        }

        logEvents.add(logEvent);

        return logEvent;
    }

    /**
    * @author Gil Avignon
    * @date 25/07/2018
    * @description Generate log unique Identifier
    * @param logEvent record
    * @return Log__c generated log Object record
    */
    public static Log__c log(LogEvent__e logEvent) {
        return new Log__c(
                Identifier__c = logEvent.Identifier__c,
                APIName__c = logEvent.APIName__c,
                ApexClass__c = logEvent.ApexClass__c,
                ApexMethod__c = logEvent.ApexMethod__c,
                CorrelationId__c = logEvent.CorrelationId__c,
                Description__c = logEvent.Description__c,
                Details__c = logEvent.Details__c,
                Type__c = logEvent.Type__c,
                Endpoint__c = logEvent.Endpoint__c,
                ExceptionType__c = logEvent.ExceptionType__c,
                RequestHeader__c = logEvent.RequestHeader__c,
                RequestBody__c = logEvent.RequestBody__c,
                ResponseHeader__c = logEvent.ResponseHeader__c,
                ResponseBody__c = logEvent.ResponseBody__c,
                ResponseStatus__c = logEvent.ResponseStatus__c,
                ResponseStatusCode__c = logEvent.ResponseStatusCode__c,
                RunningUser__c = logEvent.RunningUser__c,
                EntityId__c = logEvent.EntityId__c,
                EntityData__c = logEvent.EntityData__c,
                RecordTypeId = logEvent.RecordTypeId__c,
                StackTrace__c = logEvent.StackTrace__c
        );
    }

    /**
    * @author Gil Avignon
    * @date 25/07/2018
    * @description Generate log unique Identifier
    * @return String Generated log Identifier
    */
    public static String generateId(){
        String lastName = UserInfo.getLastName().toUpperCase();
        String firstName = UserInfo.getFirstName().toUpperCase();
        Datetime currentDate = Datetime.now();

        String generatedId = firstName.substring(0, 1) + lastName.substring(0, 2) + '-' + currentDate.format('YY')
                + currentDate.format('MM') + currentDate.format('dd') + '-' + currentDate.format('HH') + currentDate.format('mm')
                + currentDate.format('ss') + currentDate.format('SSS');

        return generatedId;
    }

    /**
    * @author Gil Avignon
    * @date 30/07/2018
    * @description Commit Debug log events
    * @return void
    */
    public static List<Database.SaveResult> commitLogEvents(){
        List<Database.SaveResult> results;
        if(logEvents.size() > 0){
            results = EventBus.publish(logEvents);
            logEvents.clear();
        }
        return results;
    }

}