force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>Object used for logging purpose (debug, callouts, exceptions...)</description>
    <label>Log</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{DD}_{0000000000}</displayFormat>
        <label>Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/ApexClass__c.field-meta.xml
<CustomField>
    <fullName>ApexClass__c</fullName>
    <description>Apex class that generates the log (from the start)</description>
    <label>Apex Class</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/ApexMethod__c.field-meta.xml
<CustomField>
    <fullName>ApexMethod__c</fullName>
    <description>Apex method that generates the log (from the start)</description>
    <label>Apex Method</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/APIName__c.field-meta.xml
<CustomField>
    <fullName>APIName__c</fullName>
    <description>API Name</description>
    <label>API Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>referential.location.v2</fullName>
            </value>
            <value>
                <fullName>shipping.shipment.v1</fullName>
            </value>
            <value>
                <fullName>WIMB</fullName>
            </value>
            <value>
                <fullName>vesseloperation.voyage.v1</fullName>
            </value>
            <value>
                <fullName>user.pingfederate.v1</fullName>
            </value>
            <value>
                <fullName>shipping.shipment.v2</fullName>
            </value>
            <value>
                <fullName>logistic.tracking.wimb</fullName>
            </value>
            <value>
                <fullName>invoicing.advanced.v1</fullName>
            </value>
            <value>
                <fullName>vesseloperation.voyage.localreferences.v1</fullName>
            </value>
            <value>
                <fullName>shipping.shipment.notification.advance.v1</fullName>
            </value>
            <value>
                <fullName>shipping.shippingdocument.v1</fullName>
            </value>
            <value>
                <fullName>shipping.shipment.shipmentrequest.v1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Log description</description>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <label>Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <description>Callout endpoint</description>
    <label>Endpoint</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/EntityId__c.field-meta.xml
<CustomField>
    <fullName>EntityId__c</fullName>
    <description>Main entity ID</description>
    <label>Entity ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Identifier__c.field-meta.xml
<CustomField>
    <fullName>Identifier__c</fullName>
    <description>Log identifier</description>
    <label>Identifier</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Log__c/fields/RequestHeader__c.field-meta.xml
<CustomField>
    <fullName>RequestHeader__c</fullName>
    <description>Request Header</description>
    <label>Request Header</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/RunningUser__c.field-meta.xml
<CustomField>
    <fullName>RunningUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Running User that generates the log record</description>
    <label>Running User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Log type (Error, debug...)</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
                <default>true</default>
                <label>Error</label>
            </value>
            <value>
                <fullName>Debug</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/recordTypes/Apex.recordType-meta.xml
<RecordType>
    <fullName>Apex</fullName>
    <active>true</active>
    <description>Apex log</description>
    <label>Apex</label>
</RecordType>

force-app/main/default/objects/LogEvent__e/LogEvent__e.object-meta.xml
<CustomObject>
    <description>Log Event</description>
    <label>LogEvent</label>
    <pluralLabel>LogsEvent</pluralLabel>
</CustomObject>

force-app/main/default/objects/LogEvent__e/fields/ApexClass__c.field-meta.xml
<CustomField>
    <fullName>ApexClass__c</fullName>
    <label>Apex Class</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/ApexMethod__c.field-meta.xml
<CustomField>
    <fullName>ApexMethod__c</fullName>
    <label>Apex Method</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/APIName__c.field-meta.xml
<CustomField>
    <fullName>APIName__c</fullName>
    <label>APiName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description</description>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <label>Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/EntityID__c.field-meta.xml
<CustomField>
    <fullName>EntityID__c</fullName>
    <label>Entity ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/Identifier__c.field-meta.xml
<CustomField>
    <fullName>Identifier__c</fullName>
    <label>Identifier</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/RecordTypeId__c.field-meta.xml
<CustomField>
    <fullName>RecordTypeId__c</fullName>
    <label>Record Type ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/RequestHeader__c.field-meta.xml
<CustomField>
    <fullName>RequestHeader__c</fullName>
    <label>Request Header</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/RunningUser__c.field-meta.xml
<CustomField>
    <fullName>RunningUser__c</fullName>
    <description>User ID that generates the log record</description>
    <label>Running User</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TRG_LogEventHandlerTest.cls
/**
* @author Gil Avignon
* @date 11/06/2019
* @description Test class for TRG_LogEventHandler
* @group Tests
*/
@IsTest
public with sharing class TRG_LogEventHandlerTest {
    private static final String FIRSTNAME_TEST = 'Test';
    private static final String LASTNAME_TEST = 'TestUser';
    private static Map<String, Id> recordTypesByDeveloperName = UTIL_RecordType.getRecordTypesDeveloper('Log__c');
    private static UTIL_TestFactory.UserFactory userFactory = new UTIL_TestFactory.UserFactory();

    @TestSetup
    static void setup() {
        User u = userFactory.createRunningUserAdministrator();
        insert u;
    }

    @isTest
    static void saveRecordsSuccess() {
        User u = [SELECT Id FROM User WHERE LastName = :LASTNAME_TEST LIMIT 1];

        System.runAs(u) {

            LogEvent__e logEvent = new LogEvent__e(
                    Identifier__c = UTIL_Logger.generateId(),
                    APIName__c = null,
                    ApexClass__c = 'C3S_TRG05LogEventHandlerTest',
                    ApexMethod__c = 'saveRecords',
                    Description__c = 'error',
                    Details__c = 'error',
                    Type__c = UTIL_Constants.LOG_TYPE_ERROR,
                    Endpoint__c = null,
                    RequestHeader__c = null,
                    RunningUser__c = UserInfo.getUserId(),
                    EntityId__c = null,
                    RecordTypeId__c = recordTypesByDeveloperName.get('Apex')
            );

            Test.startTest();
            EventBus.publish(logEvent);
            Test.stopTest();

            List<Log__c> logs = [SELECT Id FROM Log__c];
            System.assertEquals(1, logs.size());
        }
    }

    @isTest
    static void saveRecordsError() {
        User u = [SELECT Id FROM User WHERE LastName = :LASTNAME_TEST LIMIT 1];

        System.runAs(u) {

            LogEvent__e logEvent = new LogEvent__e(
                    Identifier__c = UTIL_Logger.generateId(),
                    APIName__c = 'I don\'t exist',
                    ApexClass__c = 'C3S_TRG05LogEventHandlerTest',
                    ApexMethod__c = 'saveRecords',
                    Description__c = 'error',
                    Details__c = 'error',
                    Type__c = UTIL_Constants.LOG_TYPE_ERROR,
                    Endpoint__c = null,
                    RequestHeader__c = null,
                    RunningUser__c = UserInfo.getUserId(),
                    EntityId__c = null,
                    RecordTypeId__c = recordTypesByDeveloperName.get('Apex')
            );

            Test.startTest();
            EventBus.publish(logEvent);
            Test.stopTest();

            List<Log__c> logs = [SELECT Id FROM Log__c];
            System.assertEquals(0, logs.size());
        }
    }
}