force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>Object used for logging purpose (debug, callouts, exceptions...)</description>
    <label>Log</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{DD}_{0000000000}</displayFormat>
        <label>Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/ApexClass__c.field-meta.xml
<CustomField>
    <fullName>ApexClass__c</fullName>
    <description>Apex class that generates the log (from the start)</description>
    <label>Apex Class</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/ApexMethod__c.field-meta.xml
<CustomField>
    <fullName>ApexMethod__c</fullName>
    <description>Apex method that generates the log (from the start)</description>
    <label>Apex Method</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/APIName__c.field-meta.xml
<CustomField>
    <fullName>APIName__c</fullName>
    <description>API Name</description>
    <label>API Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>referential.location.v2</fullName>
            </value>
            <value>
                <fullName>shipping.shipment.v1</fullName>
            </value>
            <value>
                <fullName>WIMB</fullName>
            </value>
            <value>
                <fullName>vesseloperation.voyage.v1</fullName>
            </value>
            <value>
                <fullName>user.pingfederate.v1</fullName>
            </value>
            <value>
                <fullName>shipping.shipment.v2</fullName>
            </value>
            <value>
                <fullName>logistic.tracking.wimb</fullName>
            </value>
            <value>
                <fullName>invoicing.advanced.v1</fullName>
            </value>
            <value>
                <fullName>vesseloperation.voyage.localreferences.v1</fullName>
            </value>
            <value>
                <fullName>shipping.shipment.notification.advance.v1</fullName>
            </value>
            <value>
                <fullName>shipping.shippingdocument.v1</fullName>
            </value>
            <value>
                <fullName>shipping.shipment.shipmentrequest.v1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Log description</description>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <description>Callout endpoint</description>
    <label>Endpoint</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Identifier__c.field-meta.xml
<CustomField>
    <fullName>Identifier__c</fullName>
    <description>Log identifier</description>
    <label>Identifier</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/LogEvent__e/LogEvent__e.object-meta.xml
<CustomObject>
    <description>Log Event</description>
    <label>LogEvent</label>
    <pluralLabel>LogsEvent</pluralLabel>
</CustomObject>

force-app/main/default/objects/LogEvent__e/fields/ApexClass__c.field-meta.xml
<CustomField>
    <fullName>ApexClass__c</fullName>
    <label>Apex Class</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/ApexMethod__c.field-meta.xml
<CustomField>
    <fullName>ApexMethod__c</fullName>
    <label>Apex Method</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/APIName__c.field-meta.xml
<CustomField>
    <fullName>APIName__c</fullName>
    <label>APiName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description</description>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/Identifier__c.field-meta.xml
<CustomField>
    <fullName>Identifier__c</fullName>
    <label>Identifier</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UTIL_LoggerTest.cls
/**
* @author Gil Avignon
* @date 14/06/2018
* @description Test class for UTIL_Logger
* @group Tests
*/
@isTest
public class UTIL_LoggerTest {

    private static final String FIRSTNAME_TEST = 'Test';
    private static final String LASTNAME_TEST = 'TestUser';
    private static UTIL_TestFactory.UserFactory userFactory = new UTIL_TestFactory.UserFactory();

    @testSetup static void setup() {
        User u = userFactory.createRunningUserAdministrator();
        insert u;
    }

    @isTest
    static void saveLog() {
        User u = [SELECT Id FROM User WHERE LastName = :LASTNAME_TEST LIMIT 1];

        System.runAs(u) {

            String description = 'Description';
            String apexClass = 'UTIL_Logger';
            String apexMethod = 'saveLog';
            String endpoint = 'https://endpoint.com';

            HttpRequest req = new HttpRequest();
            req.setHeader(UTIL_Constants.REQUEST_HEADER_TRACE_ORG, UserInfo.getOrganizationId());
            req.setEndpoint(endpoint);
            HttpResponse resp = new HttpResponse();
            resp.setBody('{"body": "example"}');

            Test.startTest();
            LogEvent__e logEvent1 = UTIL_Logger.logEvent(null, description, apexClass, apexMethod, endpoint, null, null);
            LogEvent__e logEvent2 = UTIL_Logger.logEventFromException(null, new CalloutException('ERROR'), apexClass, apexMethod, endpoint, null, null);
            LogEvent__e logEvent3 = UTIL_Logger.logEvent(null, apexClass, apexMethod, new HttpRequest(), new HttpResponse(), false);

            UTIL_Logger.commitLogEvents();
            Test.stopTest();

            Log__c l = [SELECT Id, Identifier__c, ApexClass__c, ApexMethod__c, APIName__c, Description__c, Endpoint__c FROM Log__c WHERE Identifier__c = :logEvent1.Identifier__c LIMIT 1];
            System.assertEquals(logEvent1.Identifier__c, l.Identifier__c);
            System.assertEquals(description, l.Description__c);
            System.assertEquals(apexClass, l.ApexClass__c);
            System.assertEquals(apexMethod, l.ApexMethod__c);
            System.assertEquals(null, l.APIName__c);
            System.assertEquals(endpoint, l.Endpoint__c);

            Log__c l2 = [SELECT Id, Identifier__c, ApexClass__c, ApexMethod__c, APIName__c, Description__c, Endpoint__c FROM Log__c WHERE Identifier__c = :logEvent2.Identifier__c LIMIT 1];
            System.assertEquals(logEvent2.Identifier__c, l2.Identifier__c);
            System.assertEquals('ERROR', l2.Description__c);
            System.assertEquals(apexClass, l2.ApexClass__c);
            System.assertEquals(apexMethod, l2.ApexMethod__c);
            System.assertEquals(null, l2.APIName__c);
            System.assertEquals(endpoint, l2.Endpoint__c);

            Log__c l3 = [SELECT Id, Identifier__c, ApexClass__c, ApexMethod__c, APIName__c, Description__c, Endpoint__c FROM Log__c WHERE Identifier__c = :logEvent3.Identifier__c LIMIT 1];
            System.assertEquals(logEvent3.Identifier__c, l3.Identifier__c);
            System.assertEquals(null, l3.Description__c);
            System.assertEquals(apexClass, l3.ApexClass__c);
            System.assertEquals(apexMethod, l3.ApexMethod__c);
            System.assertEquals(null, l3.APIName__c);

        }
    }

}